spring:
  application:
    name: 05_Spring_Security_UserDetailsService
  datasource:
    url: jdbc:mysql://localhost:3306/spring_user_details_service
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver  
  jpa:
    show-sql: true